# Generated by Django 2.1.1 on 2019-08-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='min_room_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='game_id',
            field=models.IntegerField(default=-1),
        ),
    ]
