# Generated by Django 2.1.1 on 2019-08-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='moves',
            field=models.IntegerField(default=0),
        ),
    ]
