# Generated by Django 2.1.1 on 2019-03-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190328_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(to='adventure.Item'),
        ),
    ]
