# Generated by Django 2.1.1 on 2018-11-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Player'),
        ),
    ]
