# Generated by Django 2.1.1 on 2019-08-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190801_0014'),
        ('adventure', '0002_auto_20190731_2101'),
    ]

    operations = [
    ]
