# Generated by Django 2.1.2 on 2018-10-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio',
            new_name='portfolio_site',
        ),
    ]
