# Generated by Django 2.1.1 on 2019-04-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_player_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adventure.Item')),
                ('itemArmorValue', models.IntegerField(default=0)),
            ],
            bases=('adventure.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adventure.Item')),
                ('itemAttackValue', models.IntegerField(default=0)),
            ],
            bases=('adventure.item',),
        ),
        migrations.AddField(
            model_name='player',
            name='baseAttackPower',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='equipedArmor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='equipedWeapon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=20),
        ),
    ]
