# Generated by Django 2.1.1 on 2019-04-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20190401_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='equipedArmor',
            new_name='equippedArmor',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='equipedWeapon',
            new_name='equippedWeapon',
        ),
    ]
