# Generated by Django 2.1.1 on 2019-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20190801_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='map_columns',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
