# Generated by Django 2.1.1 on 2019-04-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20190401_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='isArmor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='isWeapon',
            field=models.BooleanField(default=True),
        ),
    ]
