# Generated by Django 2.1.1 on 2019-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20190401_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attackPower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='baseDefense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='defense',
            field=models.IntegerField(default=0),
        ),
    ]
